---
- OneShotSelfConfirmingPricePredictionStraightMV
- OneShotSelfConfirmingPricePredictionStraightMV
- OneShotSelfConfirmingPricePredictionStraightMV
- OneShotSelfConfirmingPricePredictionStraightMV
- OneShotSelfConfirmingPricePredictionStraightMV
---
game_type: SecondPriceOneShotMarketScheduling
num_goods: 5
num_agents: 5
num_iterations: 50
num_simulations: 500000
value_upper_bound: 50
print_debug: false
update_threshold: 0.5

