---
- OSSCDP_AverageMV
- OSSCDP_AverageMV
- OSSCPP_TargetPrice
- OSSCPP_TargetPrice
---
game type: "SecondPriceOneShotMarketScheduling"
dist type: "Original"
num goods: 5
num agents: 4
num iterations: 50
num simulations: 1000000
num sample: 200
num scenario: 100
num candidate bid: 1
value upper bound: 50
print debug: "false"
print output: "true"
update threshold: 0.5
min point dist to terminate: 0.001
min distribution dist to terminate: 0.01
